### ISSUE TITLE
Improper checking of cutoff conditions in LAMMPS interface

### ISSUE THREAD

**Issue by sxie22** [uf3/uf3#108]
Incorrect checking of inner cutoffs (r_min) for ij and ik can lead to segmentation faults when small distances are encountered.

The if conditions at line 1109 and line 1119 should be carefully looked at. 

The if condition at 1109 should definitely be changed (https://github.com/uf3/uf3/blob/develop/lammps_plugin/ML-UF3/pair_uf3.cpp#L1119)

**Comment by monk-04** [comment]
I agree there's a bug! I will fix it

**Comment by monk-04** [comment]
Issue has been solved!!
