### ISSUE TITLE
Training with a Single Image

### ISSUE THREAD

**Issue by EboniWilliams** [uf3/uf3#12]
When training with a single image in the database, we get an error because the standard deviation is 0. While training with a single image is rare, I believe this should be considered a base case.

**Comment by sxie22** [comment]
The first solution that comes to mind is to exclude the standard deviation from the normalization for both terms when only one energy is present. The normalization, before applying the adjustable weighting factor, will then be 1.0 for the energy and 1/3N for the forces where N is the number of atoms in the image.
