### ISSUE TITLE
Energies mismatch between LAMMPS and Python

### ISSUE THREAD

**Issue by Fraser-Birks** [uf3/uf3#120]
I've noticed that the potential energies found from LAMMPS do not seem to match those found directly from the features in Python for the same potential and structures. Here's an illustrative example:

Taking the first configuration in the w-14.xyz example dataset, and evaluating it with the provided UF23 model for tungsten (using the python function `batched_predict`), gives an energy of -11.19098457 (which is close to the DFT value of -11.19483513). However, if one instead loads the configuration and model into LAMMPS and computes the potential energy, the value found is -4.6272762 - quite a dramatic difference.

Here's the data file and input script I used for LAMMPS:
```
(written by ASE)

1 atoms
1 atom types

0.0      3.1805004957328489  xlo xhi
0.0      3.1805004957328489  ylo yhi
0.0      1.5902502428664234  zlo zhi
                      0      1.5902502428664242      1.5902502428664242  xy xz yz

Atoms # atomic

     1   1                       0                       0                       0


Velocities

     1                       0                       0                       0

```

```
units           metal
boundary        p p p
atom_style      atomic

read_data       input_struct.data
mass            1 183.84
pair_style      uf3 3 1
pair_coeff      1 1 W_W
pair_coeff      3b 1 1 1 W_W_W

compute         1 all pe/atom
dump            d1 all custom 1 dump.lammpstrj id x y z c_1
timestep        0.001
run             0
```
The model I used was just the UF23 [example](https://github.com/uf3/uf3/blob/develop/examples/tungsten_extxyz/model_2and3.json) provided for Tungsten, which I converted to a LAMMPS potential through [this script](https://github.com/uf3/uf3/blob/develop/lammps_plugin/scripts/generate_uf3_lammps_pots.py).

**Comment by sunghjung3** [comment]
Are the forces the same though? I remember observing this too, but it turned out that it was because LAMMPS handles the 1-body offset energy differently, or something like that.

**Comment by monk-04** [comment]
@Fraser-Birks What version of UF3 LAMMPS are you using?
We recommend using the UF3 LAMMPS version from the LAMMPS github page- https://github.com/lammps/lammps

Also in UF3 LAMMPS we don't count the 1 body term, as for running MD we need only the 2- and 3-body interaction energy. The onsite energy or 1-body energy is not required

**Comment by monk-04** [comment]
So in order to match the LAMMPS energy and the energy from the features, add 1-body energy times the number of atoms to the LAMMPS energy. The 1-body energy can be found in the `json` file

**Comment by Fraser-Birks** [comment]
That's fixed it, thank you! Yes as you say, forces all match well. Depending on how much effort it is, you may want to add the one body terms to LAMMPS. I know it makes no difference for MD but people (like me) are likely to be lazy and use UF3 through the ASE LAMMPSlib calculator, and may get a bit confused if the energy it gives is wrong by an offset :slightly_smiling_face: .

**Comment by monk-04** [comment]
Thank you for the feedback. I will see if there's an easy to implement it.
