### ISSUE TITLE
Script to generate LAMMPS potential file is incorrect on main

### ISSUE THREAD

**Issue by Fraser-Birks** [uf3/uf3#123]
The LAMMPS documentation points toward [this script](https://github.com/uf3/uf3/tree/develop/lammps_plugin/scripts), but it is outdated. It looks like the correct script is on [this branch](https://github.com/uf3/uf3/tree/lammps_script_fix_document_update).

**Comment by monk-04** [comment]
Please refer to the README of the lammps plugin directory that I updated last night.

The entire lammps_plugin directory will be reorganized today

**Comment by Fraser-Birks** [comment]
No worries - just thought I'd draw your attention to it if it was an oversight!
