### ISSUE TITLE
Running UF3 for binary alloy

### ISSUE THREAD

**Issue by circs** [uf3/uf3#126]
Hi Richard,
We are looking for a UF2-3 code for binary alloys.
Alain Karma

**Comment by monk-04** [comment]
Hello @circs 

There's no separate code for binary alloys.

If you follow the [uf23_potential_demo.ipynb](https://github.com/uf3/uf3/blob/develop/examples/tungsten_extxyz/uf23_potential_demo.ipynb) in the examples directory, you will need to enter the list of elements in code block 5 as follow-
For uf2-3
```
element_list = ['Nb', 'Sn']
degree = 3
```

For uf2
```
element_list = ['Nb', 'Sn']
degree = 2
```

Just adding the elements in `element_list` sets up the appropriate objects for multi-component systems.

Also, please let me know if you need help reading the output of DFT codes and converting it to the right format. I will send you some example notebooks.

**Comment by circs** [comment]
Thanks for the feedback. We will try those steps. I discussed with Richard using an AlSi EAM potential first to test the UF2-3 training for a binary alloy and then use DFT in a second step. Richard also mentioned providing us access to VASP to train an AlAg potential but did not respond so far to my emails after the GRC conference.

**Comment by monk-04** [comment]
Ok. I will talk with Dr. Hennig about it and see how I can better assist you.

I will now be closing this issue.
