### ISSUE TITLE
uf3 with VASP

### ISSUE THREAD

**Issue by yw-fang** [uf3/uf3#24]
Hi,  Stephen, I heard about this project in Prof. Hennig's talk yesterday. I'm wondering is  the present version able to train the uf3 potentials with the VASP's forces and energies data? Thank you very much!

Yuewen

**Comment by rhennig** [comment]
Hi Yuewen, UF3 works well with VASP, which is the software we use to generate the input data of energies and forces.

Best regards,
Richard

--
Richard G. Hennig
Professor
Materials Science and Engineering, University of Florida
Associate Director
Quantum Theory Project
Email: ***@***.******@***.***>
Web: http://hennig.mse.ufl.edu<http://hennig.mse.ufl.edu/>

On Jul 29, 2022, at 11:54 AM, yw-fang ***@***.***> wrote:

﻿
[External Email]

Hi, Stephen, I heard about this project in Prof. Hennig's talk yesterday. I'm wondering is the present version able to train the uf3 potentials with the VASP's forces and energies data? Thank you very much!

Yuewen

**Comment by yw-fang** [comment]
Hi, Richard, thanks very much! Is there any example I can start with? I found there was a WIP example relevant to VASP https://github.com/uf3/uf3/tree/master/examples/vasp_project, but some files are not available there.

**Comment by sxie22** [comment]
@yw-fang Sorry for the confusion, the vasp_project example is tied to the WIP command-line interface, which should be ready in release 0.3.0. For now, please take a look at the tungsten examples, which are complete. 

The tungsten example involves only one extended XYZ file whereas we typically work with many separate vasprun.xml files in VASP. UF3 has [a function to take a subset](https://github.com/uf3/uf3/blob/f5ebdae68bb339f0561174995400c1eb6f10d490/uf3/data/io.py#L816) of ionic steps from each vasprun.xml, which is helpful to avoid oversampling around minima. For example, the [pair potential demo ](https://github.com/uf3/uf3/blob/master/examples/tungsten_extxyz/pair_potential_demo.ipynb) can be adapted to your VASP data by replacing cell 14 ("Load data") with the following:

```
import glob
pattern = "/path/to/vasp/data/vasprun*.xml"

data_paths = glob.glob(pattern)  # list of paths to vasprun files

max_samples = 50  # max samples to extract per vasprun
min_diff = 1e-3  # minimum energy difference between extracted samples

data_coordinator = io.DataCoordinator()
# parse vasprun files, enforcing max_samples and min_diff
io.parse_with_subsampling(data_paths,
                          data_coordinator,
                          max_samples=max_samples,
                          min_diff=min_diff,
                          verbose=True)
df_data = data_coordinator.consolidate()
print("Number of energies:", len(df_data))
print("Number of forces:", int(np.sum(df_data["size"]) * 3))
```

**Comment by yw-fang** [comment]
Hi, Stephen, thanks very much for your explanation. I guess the max_samples is relevant to the subset of ionic steps from vasprun.xml. There is a quick question about it: does "max_samples = 50" mean that the energies and forces of the last 50 ionic steps will be extracted?
Anyway, thanks for your code. I'll go to research its workflow with VASP a bit.

**Comment by sxie22** [comment]
@yw-fang When the number of ionic steps is larger than max_samples, a subset is selected using [farthest-point sampling](https://github.com/uf3/uf3/blob/f5ebdae68bb339f0561174995400c1eb6f10d490/uf3/util/subsample.py#L5). The first sample is the lowest-energy ionic step. Each subsequent sample is selected to maximize the "distance" (absolute value of energy difference) to all previous samples. Here is an example showing how a subset of a relaxation calculation would be selected:

```
import numpy as np
import matplotlib.pyplot as plt
from uf3.util import subsample

steps = np.arange(10)
energies = np.geomspace(1, 10, 10)[::-1]

subset = subsample.farthest_point_sampling(energies, 
                                           max_samples=5)

print("Steps:", steps)
print("Subset:", subset)

plt.plot(steps, energies, marker="s", label="snapshots")
plt.vlines(steps[subset], 0, 10, color="orange", label="selections")
plt.xlabel("Ionic Step")
plt.ylabel("Energy")
plt.legend(bbox_to_anchor=(0.85, 0.9))
plt.tight_layout()
```

![Screenshot_20220729_142625](https://user-images.githubusercontent.com/13490092/181845281-b529cd8b-4b4f-44dd-9d30-6dc7b13b9756.png)

**Comment by yw-fang** [comment]
@sxie22 Thanks very much for your demonstration of the subsample.
