### ISSUE TITLE
Multicomponent three-body contributions wrong with PBC

### ISSUE THREAD

**Issue by henk789** [uf3/uf3#30]
# Problem description

When calculating three-body energy and force contributions, results change depending on whether interactions are computed across periodic boundaries or not.

To reproduce, I have created a 10x10x10 cell with four atoms. When the atoms are placed in the middle of the cell, such that activating or deactivating PBC does not change results, contributions are computed correctly. However, if atoms are moved towards a boundary and one atom moves to the top of the box (no atoms have positions outside the box), contributions are incorrect, possibly added multiple times. 

The potential file only contains coefficients for three-body, one- and two-body coefficients are 0. All coefficients for three-body contributions are the same.

Potential file: https://pastebin.com/bfD8R0Rb
  
</details>

<details>
  <summary>Atoms in middle of cell (test_m.data)</summary>
  
  ```test.data (written by ASE) 

4    atoms 
2  atom types
0.0      10  xlo xhi
0.0      10  ylo yhi
0.0      10  zlo zhi

Atoms 

     1   2      0 4 5
     2   1      0 4 6
     3   2      0 5 5
     4   1      0 4 4
     
  ```
  
</details>

<details>
  <summary>Atoms close boundary (test_b.data)</summary>
  
  ```test.data (written by ASE) 

4    atoms 
2  atom types
0.0      10  xlo xhi
0.0      10  ylo yhi
0.0      10  zlo zhi

Atoms 

     1   2      0 4 0.5
     2   1      0 4 1.5
     3   2      0 5 0.5
     4   1      0 4 9.5
          
  ```
  
</details>

To reproduce the problem, use the files above and run:

```
# Imports
from uf3.representation import bspline
from uf3.representation import process
from uf3.util import json_io
from uf3.regression import least_squares
from uf3.forcefield import calculator
from uf3.forcefield import lammps
from uf3.util import plotting
from uf3.data import io
from uf3.data import composition
import ase

model = least_squares.WeightedLinearModel.from_json("model.json")
calc = calculator.UFCalculator(model)

test = ase.io.lammpsdata.read_lammps_data("test_m.data", style="atomic")
test.symbols = "OZrOZr"
test.pbc=True
test.wrap()
test.set_calculator(calc)
print(test.get_potential_energy())

test = ase.io.lammpsdata.read_lammps_data("test_b.data", style="atomic")
test.symbols = "OZrOZr"
test.pbc=True
test.wrap()
test.set_calculator(calc)
print(test.get_potential_energy())

```

The energies should match, since the atoms are simply moved by 5 units in z-direction, but don't:

```
-43168.42282486064
-37056.21139709316
```

While this only demonstrates the issue for the UFCalculator, it could potentially affect training if the same issue occurs when generating supercells there.

Possible causes could be symmetries, there was a fix that ensures symmetry when j and k are switched, or interactions that select the wrong central atom, but those are a shot in the dark.

**Comment by henk789** [comment]
A related issue seems to be that when constructing three-body tuples from the supercell, the atomic numbers are sorted:
https://github.com/uf3/uf3/blob/3cdae7f0077fa021a50a2fc9088c2065f02fd3ea/uf3/representation/angles.py#L423

However, when creating the hashes for the interactions, they are not sorted:
https://github.com/uf3/uf3/blob/3cdae7f0077fa021a50a2fc9088c2065f02fd3ea/uf3/data/composition.py#L163

This results in certain triangles not being evaluated at all.

Example: `[Zr, Zr, O]` interactions receive the hash `2822408` from atomic numbers `[40, 40, 8]` during construction of the `ChemicalSystem` object.
When evaluating, these interactions are sorted by atomic number, so `[Zr, Zr, O]` and `[Zr, O, Zr]` get hash `2585704` from atomic numbers `[40, 8, 40]` and are consequently completely ignored.

**Comment by mdmurshed7331-star** [comment]
DARK-XLo password
