### ISSUE TITLE
How to tabulate three body contributions?

### ISSUE THREAD

**Issue by pmrv** [uf3/uf3#51]
I've found the very helpful [function](https://github.com/uf3/uf3/blob/d9cac01e8e153663e1164f68e2f8a091acfa3c75/uf3/forcefield/lammps.py#L218C1-L218C1) to tabulate fitted potentials for `pair_style table` and got it working with standard lammps.  Now it seems that this function writes only the two body contributions.   The [lammps docs](https://docs.lammps.org/pair_threebody_table.html) lead me to belief that I should also be able to read in the three body contributions if I had them tabulated somehow.  I guess the three body plotting class already does this somehow internally, but I didn't want to poke in there too deeply yet.  Is there a way to quickly get this working or are the more involved problems that I am missing?

For now I suppose I will be able to use the `UFCalculator` for my testing, so it's not exactly urgent.

**Comment by monk-04** [comment]
Might I suggest using the lammps implementation of UF3 (can be found [here](https://github.com/monk-04/uf3/tree/lammps_implementation/lammps_plugin)) which supports both two-body and three-body interaction? You will need to re-compile lammps but you will be able to read the fitted potentials directly into LAMMPS. We also have a GPU implementation of UF3 in LAMMPS that is much faster than other ML potentials implemented in LAMMPS.

**Comment by pmrv** [comment]
Ah, didn't think to change the branch. Thanks, that should work perfectly!
