### ISSUE TITLE
Incorrect energy_weight and regularizer defination

### ISSUE THREAD

**Issue by monk-04** [uf3/uf3#52]
The square root of y_e `(np.sqrt(len(y_e)))` should be used in [this line](https://github.com/uf3/uf3/blob/master/uf3/regression/least_squares.py#L304) because in the [combined_weighted_gram](https://github.com/uf3/uf3/blob/master/uf3/regression/least_squares.py#L325) function the 'energy_weight' is getting squared.

Same applies for [force_weight](https://github.com/uf3/uf3/blob/master/uf3/regression/least_squares.py#L305).

**Comment by sunghjung3** [comment]
In addition, in the `combine_weighted_gram()` function, the `weight`, which is the relative weight between energies and forces (default: 0.5), should be outside the square.

        gram = (((weight * energy_weight) ** 2 * gram_e)
                + (((1 - weight) * force_weight) ** 2 * gram_f))
        ordinate = (((weight * energy_weight) ** 2 * ord_e)
                    + (((1 - weight) * force_weight) ** 2 * ord_f))

**Comment by monk-04** [comment]
@sunghjung3 Can you also give a short description of the regularize issue you brought up?

**Comment by sunghjung3** [comment]
The regularization hyperparameters λ also need a square root. In the code, the λ is incorporated into the regularization matrix `D`. Then to compute the least-squares estimate, `np.dot(D.T, D)` is calculated, effectively squaring the λ.

**Comment by sunghjung3** [comment]
Closing, as it was addressed in #93 and #95
