### ISSUE TITLE
When pauling electronegativity of two elements is same, interaction tuples produced are not unique

### ISSUE THREAD

**Issue by monk-04** [uf3/uf3#63]
The current code base is failing the unit test created by @JasonGibsonUfl ([here](https://github.com/uf3/uf3/pull/62#issue-1886514224)), it tests whether the interaction (and representation) tuples for system with elements of same electronegativity depend on the elements order supplied by the user. See [here](https://github.com/uf3/uf3/pull/62#issuecomment-1710788671) for an example.

@sunghjung3 mentioned he has a solution. Let's discuss the solution here. After appropriate pull request is merged I will close this issue.

**Comment by sunghjung3** [comment]
@monk-04 My bad. My enhancement was more concerned about the internal ordering of 3-body interaction tuples, but I also did not consider the case with equal electronegativities.

**Comment by monk-04** [comment]
Closing this issue, pull request 68 solved it!
