### ISSUE TITLE
generate_triplets() bug fix (pull request #61) not guaranteed to work properly

### ISSUE THREAD

**Issue by sunghjung3** [uf3/uf3#73]
In pull request #61, I made [this comment](https://github.com/uf3/uf3/pull/61#issuecomment-1710953317):

> We are relying on the fact that if the 2 neighbor elements are the same, the tuples = np.hstack((tuples[:, [0]], tuples_slice)) line will not change the order of tuples, so it is still **guaranteed** (from the line involving np.meshgrid) that there will be one row with atom numbers [a, b, c] and another row with atom numbers [a, c, b].

However, I found that this is not always guaranteed. The `tuple_slice` comes from the line `tuples_slice = np.take_along_axis(tuples[:, 1:],sort_indices,axis=1)`, which uses `sort_indices` that was generated by the line `sort_indices = np.argsort(comp_tuples[:, 1:],axis=1)`.

And what I found was that `np.argsort()` does not guarantee that the order of equal-valued entries will be preserved in the sorted list. And the result may vary depending on the computer where the code is run or the datatype of the array.

For instance, on my computer, I run this:

    import numpy as np
    x = np.array([2, 2, 2, 1, 1, 1, 3, 3, 3, 2, 2, 2, 1, 1, 1, 3, 3, 3, 2, 2, 2, 1, 1, 1, 3, 3, 3])
    print( np.argsort(x) )

The expected result is:

    array([3, 4, 5, 12, 13, 14, 21, 22, 23, 0, 1, 2, ...])

The result that I get is:

    array([13, 23, 22,  3,  4,  5, 21, 14, 12, 20, 19, 18,  0, 10,  9,  2,  1,
       11, 25, 15, 16, 17,  8,  7,  6, 24, 26])

Above, the `1` at index `13` took precedence over the `1` at index `3`.

In our case, we are sorting `comp_tuples[:, 1:]` along `axis=1`, so each sorted subarray only has 2 entries. I was not able to replicate this weird result for a vector of length 2 because I do not know the internal sorting mechanism. However, the fact that the order preservation of equal-valued entries is not guaranteed makes our solution in pull request #61 a bit unpredictable.

I am not really pushing for a fix for this issue because we are already looking to simplify `generate_triplets()` due to the [recent fix ](https://github.com/uf3/uf3/pull/66)for sorting interaction tuples by electronegativity to atomic number. But this behavior of `np.argsort()` (maybe even `np.sort()`) is something to keep in mind for future fixes.

**Comment by sunghjung3** [comment]
The `generate_triplets()` method was modified in pull request #77, removing the reliance on `np.argsort` to preserve the original ordering of equal-valued entries.

**Comment by sunghjung3** [comment]
Now at pull request #83

**Comment by monk-04** [comment]
PR #83 was merged. Should we close this issue @sunghjung3 ?

**Comment by sunghjung3** [comment]
Yes
