### ISSUE TITLE
Update reference to first UF3 paper (npj computational materials).

### ISSUE THREAD

**Issue by sxie22** [uf3/uf3#98]
The README and pypi description have links to the arxiv paper. Now that the first UF3 paper has been accepted, the arXiv link should be replaced.

https://doi.org/10.1038/s41524-023-01092-7

**Comment by mattwthompson** [comment]
This URL In the README appears to just point back to the repo; hovering over the link doesn't go where I'd expect (red box edited in):

![image](https://github.com/uf3/uf3/assets/7935382/f8801cbc-515a-4f80-a54a-3ab23a837cfe)

The rST is probably mangled, I always forget how links are supposed to work in it: https://raw.githubusercontent.com/uf3/uf3/develop/readme.rst

**Comment by monk-04** [comment]
Thank you for your comment. When I updated the page (pr #112), I messed up. I will fix it.

**Comment by monk-04** [comment]
pr #114 fixed this issue, closing!!
